server:
  port: 9999

spring:
  application:
    name: Speak_clock  

springdoc:
      swagger-ui:
         operations-sorter: method 
         path : /swagger-ui-custom.html
      api-docs:
          path: /api-docs
          